import { createCampaignStore } from "@/store/campaign-runs";
import type { CampaignModifier, CampaignTheme } from "@/lib/campaign-core";

function modsByBlock(
  order: number,
  blocks: Record<number, CampaignModifier[]>,
): CampaignModifier[] {
  const out: CampaignModifier[] = [];
  for (const [threshold, mods] of Object.entries(blocks)) {
    if (order >= Number(threshold)) out.push(...mods);
  }
  return out;
}

const BAGATELLE_TITLES = [
  "Primera Bola",
  "Cebolla Cruda",
  "Cuervo Pícaro",
  "Bumper Suave",
  "Ronda Corta",
  "Marea Baja",
  "Tilt Alegre",
  "Puertas Cerradas",
  "Rebote Muerto",
  "El Basurero",
  "Doble Bumper",
  "Calles Ciegas",
  "Gravedad Amiga",
  "Reloj Torcido",
  "Tres Bolas",
  "Sin Multi",
  "Silbato Roto",
  "Bumper Zurdo",
  "Fila Sellada",
  "La Marea",
  "Gravedad Rota",
  "Bola Pesada",
  "Punta Muerta",
  "Multibolar",
  "Rejugable",
  "Sin Piedad",
  "Bumper Loco",
  "Última Bola",
  "Desafío Final",
  "El Cuervo Ciego",
] as const;

export const useBagatelleCampaign = createCampaignStore({
  gameId: "bagatelle",
  storageKey: "cuervo:campaign:bagatelle:v1",
  displayName: "Clavo y Suerte",
  campaignName: "Encargos del Ladrón",
  levelPrefix: "BG",
  titles: BAGATELLE_TITLES,
  bossQuotes: {
    10: "El Basurero come tus fichas de a puñados.",
    20: "La Marea sube, no perdona zurdos.",
    30: "El Cuervo cierra los ojos y aún gana.",
  },
  objectiveKind: "chips",
  baseTarget: 300,
  targetGrowth: 1.14,
  baseBudget: 200,
  budgetGrowth: 1.11,
  baseReward: 200,
  rewardGrowth: 1.13,
  modifiersAt: (o) =>
    modsByBlock(o, {
      6: [{ kind: "time-cap", seconds: 180 }],
      11: [{ kind: "chip-cap", loss: 150 }],
      16: [{ kind: "min-bet", min: 25 }],
      21: [{ kind: "tax", percent: 0.1 }],
      26: [{ kind: "sabotage", everyN: 8 }],
    }),
} satisfies CampaignTheme);

const BLACKJACK_TITLES = [
  "Casino Vacío",
  "Mesa Baja",
  "Crupier Distraído",
  "Manos Cortas",
  "Doblá y Ganá",
  "Zapato Fino",
  "Split Prohibido",
  "Sin Rendirse",
  "Ojo del Crupier",
  "Ley 6:5",
  "Zapato Cargado",
  "Diez Escaso",
  "Mano Blanda",
  "Sin Doblar",
  "Rondas Rápidas",
  "As Traidor",
  "Torneo del Sótano",
  "Sin Seguro",
  "Corte Sesgada",
  "El Contador",
  "Zapato de Piedra",
  "Solo Face Cards",
  "Mesa Corrupta",
  "Pagos Cortos",
  "Mano Muerta",
  "Sabotaje Suave",
  "Desafío 21",
  "La Ruleta del As",
  "Doble Naipe",
  "El Crupier Ciego",
] as const;

export const useBlackjackCampaign = createCampaignStore({
  gameId: "blackjack",
  storageKey: "cuervo:campaign:blackjack:v1",
  displayName: "Filo de Veintiuno",
  campaignName: "Encargos del Crupier",
  levelPrefix: "BJ",
  titles: BLACKJACK_TITLES,
  bossQuotes: {
    10: "Pagamos 6 a 5, aguantá si podés.",
    20: "El Contador ya sabe tu próxima carta.",
    30: "El Crupier Ciego no falla. Nunca.",
  },
  objectiveKind: "events",
  baseTarget: 3,
  targetGrowth: 1.11,
  baseBudget: 400,
  budgetGrowth: 1.12,
  baseReward: 300,
  rewardGrowth: 1.14,
  modifiersAt: (o) =>
    modsByBlock(o, {
      6: [{ kind: "no-safe", label: "sin seguro" }],
      11: [{ kind: "time-cap", seconds: 300 }],
      16: [{ kind: "min-bet", min: 50 }],
      21: [{ kind: "tax", percent: 0.15 }],
      26: [{ kind: "chip-cap", loss: 300 }],
    }),
} satisfies CampaignTheme);

const ESCOBA_TITLES = [
  "Primera Barrida",
  "Sietes Sueltos",
  "Oros al Rincón",
  "Suma 15",
  "Contando Cartas",
  "Doña Beata",
  "El Contador Chico",
  "Cortas Rápidas",
  "Mesa Corta",
  "La Beata",
  "Oro Quema",
  "Contador Lento",
  "Rival Lector",
  "Escoba Doble",
  "Ronda Ciega",
  "Sietes Marcados",
  "Palo Prohibido",
  "Cartas Cortadas",
  "Mesa Trucada",
  "El Contador",
  "Oro Sagrado",
  "Setenta Duro",
  "Sin Escobas",
  "Rival Perfecto",
  "Cartas Nubladas",
  "Doble Beata",
  "Desafío Escoba",
  "Última Mano",
  "Silencio de Fichas",
  "El Cuervo Escobista",
] as const;

export const useEscobaCampaign = createCampaignStore({
  gameId: "escoba",
  storageKey: "cuervo:campaign:escoba:v1",
  displayName: "Barrido de Quince",
  campaignName: "Encargos de la Beata",
  levelPrefix: "ES",
  titles: ESCOBA_TITLES,
  bossQuotes: {
    10: "La Beata reza mientras vos perdés oros.",
    20: "El Contador sabe qué tenés en la mano.",
    30: "El Cuervo Escobista barrió mesas mejores.",
  },
  objectiveKind: "events",
  baseTarget: 3,
  targetGrowth: 1.09,
  baseBudget: 300,
  budgetGrowth: 1.1,
  baseReward: 250,
  rewardGrowth: 1.13,
  modifiersAt: (o) =>
    modsByBlock(o, {
      6: [{ kind: "time-cap", seconds: 240 }],
      11: [{ kind: "chip-cap", loss: 200 }],
      16: [{ kind: "no-safe", label: "sin barrer" }],
      21: [{ kind: "sabotage", everyN: 4 }],
      26: [{ kind: "tax", percent: 0.2 }],
    }),
} satisfies CampaignTheme);

const RULETA_TITLES = [
  "Rojo o Negro",
  "Docena Baja",
  "Par o Impar",
  "Columna Simple",
  "Pleno Suerte",
  "Voisins Cortos",
  "Orphelins Sueltos",
  "Tiers Ajustado",
  "Doble Cero",
  "El Croupier Ciego",
  "Rueda Torcida",
  "Chip Bajo",
  "Números Fríos",
  "Vecinos Muertos",
  "Pleno Encadenado",
  "Docena Prohibida",
  "Rueda Lenta",
  "Sesgo Rojo",
  "Sesgo Negro",
  "La Rueda Trucada",
  "Pleno Doble",
  "Bola Fría",
  "Encadenar 3",
  "Máximo Rígido",
  "Cero Frecuente",
  "Sin Externas",
  "Desafío Ruleta",
  "Última Bola",
  "Silencio del Croupier",
  "El Cuervo Croupier",
] as const;

export const useRuletaCampaign = createCampaignStore({
  gameId: "ruleta",
  storageKey: "cuervo:campaign:ruleta:v1",
  displayName: "La Rueda del Cuervo",
  campaignName: "Encargos del Croupier",
  levelPrefix: "RU",
  titles: RULETA_TITLES,
  bossQuotes: {
    10: "El Croupier Ciego paga cuando quiere.",
    20: "La Rueda Trucada muerde antes de girar.",
    30: "El Cuervo Croupier gira una sola vez.",
  },
  objectiveKind: "chips",
  baseTarget: 600,
  targetGrowth: 1.16,
  baseBudget: 500,
  budgetGrowth: 1.12,
  baseReward: 350,
  rewardGrowth: 1.14,
  modifiersAt: (o) =>
    modsByBlock(o, {
      6: [{ kind: "no-safe", label: "sin externas" }],
      11: [{ kind: "time-cap", seconds: 300 }],
      16: [{ kind: "tax", percent: 0.12 }],
      21: [{ kind: "min-bet", min: 100 }],
      26: [{ kind: "chip-cap", loss: 400 }],
    }),
} satisfies CampaignTheme);

const DADOS_TITLES = [
  "Pase Fácil",
  "Duro Suave",
  "Sin Siete",
  "Come Simple",
  "Campo Corto",
  "Duros Encadenados",
  "Come Lento",
  "Odds Cortas",
  "Siete Traidor",
  "El Tuerto",
  "Dados Cargados",
  "Campo Prohibido",
  "Apuesta Mínima Alta",
  "Salida Infernal",
  "Reloj Corto",
  "Duros en Cadena",
  "Odds Máximas",
  "Boxman Sesgado",
  "Punto 4 Único",
  "La Bruja del 7",
  "Cargados y Rápidos",
  "Come Silencioso",
  "Campo Vacío",
  "Sin Odds",
  "Punto Cambia",
  "Odds Truncadas",
  "Desafío de Dados",
  "Última Tirada",
  "Silencio del Boxman",
  "El Cuervo Dado",
] as const;

export const useDadosCampaign = createCampaignStore({
  gameId: "dados",
  storageKey: "cuervo:campaign:dados:v1",
  displayName: "Cinco Huesos",
  campaignName: "Encargos del Boxman",
  levelPrefix: "DA",
  titles: DADOS_TITLES,
  bossQuotes: {
    10: "El Tuerto fuerza el uno cuando le conviene.",
    20: "La Bruja del 7 canta antes de tirar.",
    30: "El Cuervo Dado no cuenta, decide.",
  },
  objectiveKind: "chips",
  baseTarget: 400,
  targetGrowth: 1.15,
  baseBudget: 350,
  budgetGrowth: 1.12,
  baseReward: 250,
  rewardGrowth: 1.14,
  modifiersAt: (o) =>
    modsByBlock(o, {
      6: [{ kind: "time-cap", seconds: 240 }],
      11: [{ kind: "min-bet", min: 50 }],
      16: [{ kind: "tax", percent: 0.12 }],
      21: [{ kind: "no-safe", label: "sin odds" }],
      26: [{ kind: "chip-cap", loss: 300 }],
    }),
} satisfies CampaignTheme);

const SOLITARIO_TITLES = [
  "Baraja Nueva",
  "Robo de 1",
  "Reparto Ilimitado",
  "Fundaciones Amables",
  "Primera Corona",
  "Robo de 3",
  "Un Reparto",
  "Reloj Corto",
  "Sin Deshacer",
  "El Naipe Perdido",
  "Fundaciones Rotan",
  "Deshacer Limitado",
  "Sabotaje Suave",
  "Sin Ayudas",
  "Mesa Trucada",
  "Doble Robo de 3",
  "Cero Deshacer",
  "Reloj Cruel",
  "Fundaciones Ocultas",
  "La Baraja Rota",
  "Reloj Rojo",
  "Sin Reparto",
  "Sabotaje 1/12",
  "Deshacer Cero",
  "Fundaciones Truncadas",
  "Sabotaje 1/6",
  "Desafío Klondike",
  "Última Corona",
  "Silencio de la Baraja",
  "El Cuervo Solitario",
] as const;

export const useSolitarioCampaign = createCampaignStore({
  gameId: "solitario",
  storageKey: "cuervo:campaign:solitario:v1",
  displayName: "La Mano Muerta",
  campaignName: "Encargos del Solitario",
  levelPrefix: "SO",
  titles: SOLITARIO_TITLES,
  bossQuotes: {
    10: "El Naipe Perdido no vuelve a la baraja.",
    20: "La Baraja Rota se reordena a mitad de camino.",
    30: "El Cuervo Solitario ya vio tu partida.",
  },
  objectiveKind: "events",
  baseTarget: 1,
  targetGrowth: 1.0,
  baseBudget: 3,
  budgetGrowth: 0.97,
  baseReward: 350,
  rewardGrowth: 1.14,
  modifiersAt: (o) =>
    modsByBlock(o, {
      6: [{ kind: "no-safe", label: "sin undo" }],
      11: [{ kind: "time-cap", seconds: 480 }],
      16: [{ kind: "chip-cap", loss: 2 }],
      21: [{ kind: "sabotage", everyN: 12 }],
      26: [{ kind: "tax", percent: 0.2 }],
    }),
} satisfies CampaignTheme);

export const CAMPAIGN_STORES = {
  bagatelle: useBagatelleCampaign,
  blackjack: useBlackjackCampaign,
  escoba: useEscobaCampaign,
  ruleta: useRuletaCampaign,
  dados: useDadosCampaign,
  solitario: useSolitarioCampaign,
} as const;

export type CampaignGameId = keyof typeof CAMPAIGN_STORES;
