export interface HostessPlaystyle {
  id: string;
  label: string;
  endgamePush: number;
  comebackFactor: number;
  riskTolerance: number;
  bluffTiming: number;
  counterPunch: number;
  openingBook: number;
}

const STYLES: Record<string, HostessPlaystyle> = {
  eulalia: {
    id: "eulalia",
    label: "Matemática de sótano",
    endgamePush: 0.85,
    comebackFactor: 0.8,
    riskTolerance: 0.3,
    bluffTiming: 0.85,
    counterPunch: 0.7,
    openingBook: 0.9,
  },
  hernestina: {
    id: "hernestina",
    label: "Bahiana temeraria",
    endgamePush: 0.5,
    comebackFactor: 0.35,
    riskTolerance: 0.85,
    bluffTiming: 0.3,
    counterPunch: 0.55,
    openingBook: 0.2,
  },

  zulme: {
    id: "zulme",
    label: "Trampera metódica",
    endgamePush: 0.9,
    comebackFactor: 0.65,
    riskTolerance: 0.4,
    bluffTiming: 0.9,
    counterPunch: 0.8,
    openingBook: 0.75,
  },
  alice: {
    id: "alice",
    label: "Trampera metódica",
    endgamePush: 0.9,
    comebackFactor: 0.65,
    riskTolerance: 0.4,
    bluffTiming: 0.9,
    counterPunch: 0.8,
    openingBook: 0.75,
  },
  luisa: {
    id: "luisa",
    label: "Descarada del barrio",
    endgamePush: 0.4,
    comebackFactor: 0.3,
    riskTolerance: 0.9,
    bluffTiming: 0.2,
    counterPunch: 0.45,
    openingBook: 0.15,
  },

  zelda: {
    id: "zelda",
    label: "Intuitiva profética",
    endgamePush: 0.7,
    comebackFactor: 0.6,
    riskTolerance: 0.55,
    bluffTiming: 0.5,
    counterPunch: 0.5,
    openingBook: 0.55,
  },
  salome: {
    id: "salome",
    label: "Andaluza encendida",
    endgamePush: 0.55,
    comebackFactor: 0.4,
    riskTolerance: 0.85,
    bluffTiming: 0.35,
    counterPunch: 0.6,
    openingBook: 0.3,
  },

  pilar: {
    id: "pilar",
    label: "Memoria de elefante",
    endgamePush: 0.75,
    comebackFactor: 0.85,
    riskTolerance: 0.25,
    bluffTiming: 0.7,
    counterPunch: 0.75,
    openingBook: 0.95,
  },
  ines: {
    id: "ines",
    label: "Cauta tímida",
    endgamePush: 0.6,
    comebackFactor: 0.7,
    riskTolerance: 0.3,
    bluffTiming: 0.6,
    counterPunch: 0.4,
    openingBook: 0.65,
  },

  anahit: {
    id: "anahit",
    label: "Estratega litúrgica",
    endgamePush: 0.8,
    comebackFactor: 0.75,
    riskTolerance: 0.4,
    bluffTiming: 0.6,
    counterPunch: 0.85,
    openingBook: 0.95,
  },
  kelia: {
    id: "kelia",
    label: "Ofensiva veloz",
    endgamePush: 0.55,
    comebackFactor: 0.45,
    riskTolerance: 0.8,
    bluffTiming: 0.3,
    counterPunch: 0.7,
    openingBook: 0.5,
  },

  yolanda: {
    id: "yolanda",
    label: "Tejedora habanera",
    endgamePush: 0.8,
    comebackFactor: 0.7,
    riskTolerance: 0.35,
    bluffTiming: 0.55,
    counterPunch: 0.7,
    openingBook: 0.85,
  },
  isabel: {
    id: "isabel",
    label: "Impaciente cortante",
    endgamePush: 0.5,
    comebackFactor: 0.4,
    riskTolerance: 0.75,
    bluffTiming: 0.3,
    counterPunch: 0.55,
    openingBook: 0.35,
  },

  mirla: {
    id: "mirla",
    label: "Terraza soñadora",
    endgamePush: 0.65,
    comebackFactor: 0.6,
    riskTolerance: 0.45,
    bluffTiming: 0.5,
    counterPunch: 0.65,
    openingBook: 0.8,
  },
  kovia: {
    id: "kovia",
    label: "Ajedrecista rusa",
    endgamePush: 0.9,
    comebackFactor: 0.85,
    riskTolerance: 0.35,
    bluffTiming: 0.55,
    counterPunch: 0.9,
    openingBook: 0.98,
  },

  jade: {
    id: "jade",
    label: "Serena precisa",
    endgamePush: 0.85,
    comebackFactor: 0.8,
    riskTolerance: 0.3,
    bluffTiming: 0.75,
    counterPunch: 0.7,
    openingBook: 0.9,
  },
  corvina: {
    id: "corvina",
    label: "Anfitriona letal",
    endgamePush: 0.95,
    comebackFactor: 0.9,
    riskTolerance: 0.45,
    bluffTiming: 0.85,
    counterPunch: 0.85,
    openingBook: 0.9,
  },
  madge: {
    id: "madge",
    label: "Póker sin piedad",
    endgamePush: 0.85,
    comebackFactor: 0.75,
    riskTolerance: 0.5,
    bluffTiming: 0.8,
    counterPunch: 0.8,
    openingBook: 0.85,
  },
  remedios: {
    id: "remedios",
    label: "Pulga tramposa",
    endgamePush: 0.7,
    comebackFactor: 0.55,
    riskTolerance: 0.75,
    bluffTiming: 0.4,
    counterPunch: 0.65,
    openingBook: 0.55,
  },
  bettie: {
    id: "bettie",
    label: "Blackjack fría",
    endgamePush: 0.8,
    comebackFactor: 0.75,
    riskTolerance: 0.35,
    bluffTiming: 0.65,
    counterPunch: 0.7,
    openingBook: 0.9,
  },

  luciera: {
    id: "luciera",
    label: "Croupier de neón",
    endgamePush: 0.75,
    comebackFactor: 0.6,
    riskTolerance: 0.55,
    bluffTiming: 0.6,
    counterPunch: 0.65,
    openingBook: 0.8,
  },
  clara: {
    id: "clara",
    label: "Suplente serena",
    endgamePush: 0.55,
    comebackFactor: 0.5,
    riskTolerance: 0.6,
    bluffTiming: 0.45,
    counterPunch: 0.5,
    openingBook: 0.55,
  },

  valois: {
    id: "valois",
    label: "Contadora silenciosa",
    endgamePush: 0.7,
    comebackFactor: 0.8,
    riskTolerance: 0.25,
    bluffTiming: 0.55,
    counterPunch: 0.6,
    openingBook: 0.95,
  },

  lin: {
    id: "lin",
    label: "Descarte punzante",
    endgamePush: 0.6,
    comebackFactor: 0.5,
    riskTolerance: 0.7,
    bluffTiming: 0.4,
    counterPunch: 0.75,
    openingBook: 0.55,
  },

  dorothy: {
    id: "dorothy",
    label: "Farolera novata",
    endgamePush: 0.55,
    comebackFactor: 0.4,
    riskTolerance: 0.8,
    bluffTiming: 0.25,
    counterPunch: 0.45,
    openingBook: 0.3,
  },

  lola: {
    id: "lola",
    label: "Reina del abanico",
    endgamePush: 0.75,
    comebackFactor: 0.65,
    riskTolerance: 0.55,
    bluffTiming: 0.6,
    counterPunch: 0.6,
    openingBook: 0.7,
  },
  shauna: {
    id: "shauna",
    label: "Rebote impredecible",
    endgamePush: 0.5,
    comebackFactor: 0.4,
    riskTolerance: 0.85,
    bluffTiming: 0.3,
    counterPunch: 0.5,
    openingBook: 0.35,
  },

  daphne: {
    id: "daphne",
    label: "Diva de tragaperras",
    endgamePush: 0.65,
    comebackFactor: 0.55,
    riskTolerance: 0.7,
    bluffTiming: 0.5,
    counterPunch: 0.55,
    openingBook: 0.6,
  },
  popelin: {
    id: "popelin",
    label: "Novia de la palanca",
    endgamePush: 0.45,
    comebackFactor: 0.35,
    riskTolerance: 0.9,
    bluffTiming: 0.2,
    counterPunch: 0.4,
    openingBook: 0.25,
  },

  miriam: {
    id: "miriam",
    label: "Suplente trilera",
    endgamePush: 0.6,
    comebackFactor: 0.45,
    riskTolerance: 0.8,
    bluffTiming: 0.35,
    counterPunch: 0.55,
    openingBook: 0.4,
  },

  perla: {
    id: "perla",
    label: "Marea rítmica",
    endgamePush: 0.7,
    comebackFactor: 0.65,
    riskTolerance: 0.5,
    bluffTiming: 0.55,
    counterPunch: 0.6,
    openingBook: 0.75,
  },
  richiane: {
    id: "richiane",
    label: "Barra impaciente",
    endgamePush: 0.55,
    comebackFactor: 0.45,
    riskTolerance: 0.75,
    bluffTiming: 0.35,
    counterPunch: 0.5,
    openingBook: 0.45,
  },

  crescencia: {
    id: "crescencia",
    label: "Puntería de almacén",
    endgamePush: 0.7,
    comebackFactor: 0.55,
    riskTolerance: 0.45,
    bluffTiming: 0.55,
    counterPunch: 0.6,
    openingBook: 0.75,
  },
  secue: {
    id: "secue",
    label: "Tiro apurado",
    endgamePush: 0.5,
    comebackFactor: 0.4,
    riskTolerance: 0.8,
    bluffTiming: 0.3,
    counterPunch: 0.45,
    openingBook: 0.35,
  },

  opal: {
    id: "opal",
    label: "Cuadrícula obsesiva",
    endgamePush: 0.85,
    comebackFactor: 0.8,
    riskTolerance: 0.2,
    bluffTiming: 0.7,
    counterPunch: 0.65,
    openingBook: 0.95,
  },
  xinie: {
    id: "xinie",
    label: "Deductora paciente",
    endgamePush: 0.65,
    comebackFactor: 0.7,
    riskTolerance: 0.25,
    bluffTiming: 0.55,
    counterPunch: 0.5,
    openingBook: 0.8,
  },

  may: {
    id: "may",
    label: "Envenenadora fría",
    endgamePush: 0.9,
    comebackFactor: 0.8,
    riskTolerance: 0.4,
    bluffTiming: 0.85,
    counterPunch: 0.75,
    openingBook: 0.85,
  },
  eriena: {
    id: "eriena",
    label: "Cata suspicaz",
    endgamePush: 0.65,
    comebackFactor: 0.6,
    riskTolerance: 0.55,
    bluffTiming: 0.6,
    counterPunch: 0.65,
    openingBook: 0.7,
  },

  celeste: {
    id: "celeste",
    label: "Copla en escena",
    endgamePush: 0.8,
    comebackFactor: 0.7,
    riskTolerance: 0.5,
    bluffTiming: 0.65,
    counterPunch: 0.65,
    openingBook: 0.85,
  },
  safiro: {
    id: "safiro",
    label: "Coplera suplente",
    endgamePush: 0.55,
    comebackFactor: 0.55,
    riskTolerance: 0.65,
    bluffTiming: 0.45,
    counterPunch: 0.5,
    openingBook: 0.55,
  },

  vita: {
    id: "vita",
    label: "Cuchillas del solitario",
    endgamePush: 0.75,
    comebackFactor: 0.7,
    riskTolerance: 0.45,
    bluffTiming: 0.6,
    counterPunch: 0.65,
    openingBook: 0.75,
  },
  eloise: {
    id: "eloise",
    label: "Condesa metódica",
    endgamePush: 0.7,
    comebackFactor: 0.75,
    riskTolerance: 0.3,
    bluffTiming: 0.55,
    counterPunch: 0.55,
    openingBook: 0.9,
  },
};

const DEFAULT: HostessPlaystyle = {
  id: "default",
  label: "Equilibrada",
  endgamePush: 0.6,
  comebackFactor: 0.5,
  riskTolerance: 0.5,
  bluffTiming: 0.5,
  counterPunch: 0.5,
  openingBook: 0.6,
};

export function getHostessPlaystyle(id: string | null | undefined): HostessPlaystyle {
  if (!id) return DEFAULT;
  return STYLES[id] ?? DEFAULT;
}
