/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as BagatelleRouteImport } from './routes/bagatelle'
import { Route as BlackjackRouteImport } from './routes/blackjack'
import { Route as CamerinosRouteImport } from './routes/camerinos'
import { Route as ChinchonRouteImport } from './routes/chinchon'
import { Route as DadosRouteImport } from './routes/dados'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as DificultadRouteImport } from './routes/dificultad'
import { Route as EncargosRouteImport } from './routes/encargos'
import { Route as EscobaRouteImport } from './routes/escoba'
import { Route as EstadisticasRouteImport } from './routes/estadisticas'
import { Route as LogrosRouteImport } from './routes/logros'
import { Route as MahjongRouteImport } from './routes/mahjong'
import { Route as PokerRouteImport } from './routes/poker'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as ProgresoRouteImport } from './routes/progreso'
import { Route as ReglasRouteImport } from './routes/reglas'
import { Route as RuletaRouteImport } from './routes/ruleta'
import { Route as SindicatoRouteImport } from './routes/sindicato'
import { Route as SingleRouteImport } from './routes/single'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SolitarioRouteImport } from './routes/solitario'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as TorneoRouteImport } from './routes/torneo'
import { Route as TrucoRouteImport } from './routes/truco'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const BagatelleRoute = BagatelleRouteImport.update({
  id: '/bagatelle',
  path: '/bagatelle',
  getParentRoute: () => rootRouteImport,
} as any)
const BlackjackRoute = BlackjackRouteImport.update({
  id: '/blackjack',
  path: '/blackjack',
  getParentRoute: () => rootRouteImport,
} as any)
const CamerinosRoute = CamerinosRouteImport.update({
  id: '/camerinos',
  path: '/camerinos',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinchonRoute = ChinchonRouteImport.update({
  id: '/chinchon',
  path: '/chinchon',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosRoute = DadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const DificultadRoute = DificultadRouteImport.update({
  id: '/dificultad',
  path: '/dificultad',
  getParentRoute: () => rootRouteImport,
} as any)
const EncargosRoute = EncargosRouteImport.update({
  id: '/encargos',
  path: '/encargos',
  getParentRoute: () => rootRouteImport,
} as any)
const EscobaRoute = EscobaRouteImport.update({
  id: '/escoba',
  path: '/escoba',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadisticasRoute = EstadisticasRouteImport.update({
  id: '/estadisticas',
  path: '/estadisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const LogrosRoute = LogrosRouteImport.update({
  id: '/logros',
  path: '/logros',
  getParentRoute: () => rootRouteImport,
} as any)
const MahjongRoute = MahjongRouteImport.update({
  id: '/mahjong',
  path: '/mahjong',
  getParentRoute: () => rootRouteImport,
} as any)
const PokerRoute = PokerRouteImport.update({
  id: '/poker',
  path: '/poker',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgresoRoute = ProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglasRoute = ReglasRouteImport.update({
  id: '/reglas',
  path: '/reglas',
  getParentRoute: () => rootRouteImport,
} as any)
const RuletaRoute = RuletaRouteImport.update({
  id: '/ruleta',
  path: '/ruleta',
  getParentRoute: () => rootRouteImport,
} as any)
const SindicatoRoute = SindicatoRouteImport.update({
  id: '/sindicato',
  path: '/sindicato',
  getParentRoute: () => rootRouteImport,
} as any)
const SingleRoute = SingleRouteImport.update({
  id: '/single',
  path: '/single',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SolitarioRoute = SolitarioRouteImport.update({
  id: '/solitario',
  path: '/solitario',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const TorneoRoute = TorneoRouteImport.update({
  id: '/torneo',
  path: '/torneo',
  getParentRoute: () => rootRouteImport,
} as any)
const TrucoRoute = TrucoRouteImport.update({
  id: '/truco',
  path: '/truco',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/bagatelle': typeof BagatelleRoute
  '/blackjack': typeof BlackjackRoute
  '/camerinos': typeof CamerinosRoute
  '/chinchon': typeof ChinchonRoute
  '/dados': typeof DadosRoute
  '/diario': typeof DiarioRoute
  '/dificultad': typeof DificultadRoute
  '/encargos': typeof EncargosRoute
  '/escoba': typeof EscobaRoute
  '/estadisticas': typeof EstadisticasRoute
  '/logros': typeof LogrosRoute
  '/mahjong': typeof MahjongRoute
  '/poker': typeof PokerRoute
  '/privacidad': typeof PrivacidadRoute
  '/progreso': typeof ProgresoRoute
  '/reglas': typeof ReglasRoute
  '/ruleta': typeof RuletaRoute
  '/sindicato': typeof SindicatoRoute
  '/single': typeof SingleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solitario': typeof SolitarioRoute
  '/tables': typeof TablesRoute
  '/torneo': typeof TorneoRoute
  '/truco': typeof TrucoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/bagatelle': typeof BagatelleRoute
  '/blackjack': typeof BlackjackRoute
  '/camerinos': typeof CamerinosRoute
  '/chinchon': typeof ChinchonRoute
  '/dados': typeof DadosRoute
  '/diario': typeof DiarioRoute
  '/dificultad': typeof DificultadRoute
  '/encargos': typeof EncargosRoute
  '/escoba': typeof EscobaRoute
  '/estadisticas': typeof EstadisticasRoute
  '/logros': typeof LogrosRoute
  '/mahjong': typeof MahjongRoute
  '/poker': typeof PokerRoute
  '/privacidad': typeof PrivacidadRoute
  '/progreso': typeof ProgresoRoute
  '/reglas': typeof ReglasRoute
  '/ruleta': typeof RuletaRoute
  '/sindicato': typeof SindicatoRoute
  '/single': typeof SingleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solitario': typeof SolitarioRoute
  '/tables': typeof TablesRoute
  '/torneo': typeof TorneoRoute
  '/truco': typeof TrucoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/bagatelle': typeof BagatelleRoute
  '/blackjack': typeof BlackjackRoute
  '/camerinos': typeof CamerinosRoute
  '/chinchon': typeof ChinchonRoute
  '/dados': typeof DadosRoute
  '/diario': typeof DiarioRoute
  '/dificultad': typeof DificultadRoute
  '/encargos': typeof EncargosRoute
  '/escoba': typeof EscobaRoute
  '/estadisticas': typeof EstadisticasRoute
  '/logros': typeof LogrosRoute
  '/mahjong': typeof MahjongRoute
  '/poker': typeof PokerRoute
  '/privacidad': typeof PrivacidadRoute
  '/progreso': typeof ProgresoRoute
  '/reglas': typeof ReglasRoute
  '/ruleta': typeof RuletaRoute
  '/sindicato': typeof SindicatoRoute
  '/single': typeof SingleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solitario': typeof SolitarioRoute
  '/tables': typeof TablesRoute
  '/torneo': typeof TorneoRoute
  '/truco': typeof TrucoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/bagatelle'
    | '/blackjack'
    | '/camerinos'
    | '/chinchon'
    | '/dados'
    | '/diario'
    | '/dificultad'
    | '/encargos'
    | '/escoba'
    | '/estadisticas'
    | '/logros'
    | '/mahjong'
    | '/poker'
    | '/privacidad'
    | '/progreso'
    | '/reglas'
    | '/ruleta'
    | '/sindicato'
    | '/single'
    | '/sitemap.xml'
    | '/solitario'
    | '/tables'
    | '/torneo'
    | '/truco'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/bagatelle'
    | '/blackjack'
    | '/camerinos'
    | '/chinchon'
    | '/dados'
    | '/diario'
    | '/dificultad'
    | '/encargos'
    | '/escoba'
    | '/estadisticas'
    | '/logros'
    | '/mahjong'
    | '/poker'
    | '/privacidad'
    | '/progreso'
    | '/reglas'
    | '/ruleta'
    | '/sindicato'
    | '/single'
    | '/sitemap.xml'
    | '/solitario'
    | '/tables'
    | '/torneo'
    | '/truco'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/bagatelle'
    | '/blackjack'
    | '/camerinos'
    | '/chinchon'
    | '/dados'
    | '/diario'
    | '/dificultad'
    | '/encargos'
    | '/escoba'
    | '/estadisticas'
    | '/logros'
    | '/mahjong'
    | '/poker'
    | '/privacidad'
    | '/progreso'
    | '/reglas'
    | '/ruleta'
    | '/sindicato'
    | '/single'
    | '/sitemap.xml'
    | '/solitario'
    | '/tables'
    | '/torneo'
    | '/truco'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  BagatelleRoute: typeof BagatelleRoute
  BlackjackRoute: typeof BlackjackRoute
  CamerinosRoute: typeof CamerinosRoute
  ChinchonRoute: typeof ChinchonRoute
  DadosRoute: typeof DadosRoute
  DiarioRoute: typeof DiarioRoute
  DificultadRoute: typeof DificultadRoute
  EncargosRoute: typeof EncargosRoute
  EscobaRoute: typeof EscobaRoute
  EstadisticasRoute: typeof EstadisticasRoute
  LogrosRoute: typeof LogrosRoute
  MahjongRoute: typeof MahjongRoute
  PokerRoute: typeof PokerRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ProgresoRoute: typeof ProgresoRoute
  ReglasRoute: typeof ReglasRoute
  RuletaRoute: typeof RuletaRoute
  SindicatoRoute: typeof SindicatoRoute
  SingleRoute: typeof SingleRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolitarioRoute: typeof SolitarioRoute
  TablesRoute: typeof TablesRoute
  TorneoRoute: typeof TorneoRoute
  TrucoRoute: typeof TrucoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bagatelle': {
      id: '/bagatelle'
      path: '/bagatelle'
      fullPath: '/bagatelle'
      preLoaderRoute: typeof BagatelleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blackjack': {
      id: '/blackjack'
      path: '/blackjack'
      fullPath: '/blackjack'
      preLoaderRoute: typeof BlackjackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camerinos': {
      id: '/camerinos'
      path: '/camerinos'
      fullPath: '/camerinos'
      preLoaderRoute: typeof CamerinosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chinchon': {
      id: '/chinchon'
      path: '/chinchon'
      fullPath: '/chinchon'
      preLoaderRoute: typeof ChinchonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dados': {
      id: '/dados'
      path: '/dados'
      fullPath: '/dados'
      preLoaderRoute: typeof DadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dificultad': {
      id: '/dificultad'
      path: '/dificultad'
      fullPath: '/dificultad'
      preLoaderRoute: typeof DificultadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encargos': {
      id: '/encargos'
      path: '/encargos'
      fullPath: '/encargos'
      preLoaderRoute: typeof EncargosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escoba': {
      id: '/escoba'
      path: '/escoba'
      fullPath: '/escoba'
      preLoaderRoute: typeof EscobaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estadisticas': {
      id: '/estadisticas'
      path: '/estadisticas'
      fullPath: '/estadisticas'
      preLoaderRoute: typeof EstadisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logros': {
      id: '/logros'
      path: '/logros'
      fullPath: '/logros'
      preLoaderRoute: typeof LogrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mahjong': {
      id: '/mahjong'
      path: '/mahjong'
      fullPath: '/mahjong'
      preLoaderRoute: typeof MahjongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poker': {
      id: '/poker'
      path: '/poker'
      fullPath: '/poker'
      preLoaderRoute: typeof PokerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progreso': {
      id: '/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof ProgresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglas': {
      id: '/reglas'
      path: '/reglas'
      fullPath: '/reglas'
      preLoaderRoute: typeof ReglasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ruleta': {
      id: '/ruleta'
      path: '/ruleta'
      fullPath: '/ruleta'
      preLoaderRoute: typeof RuletaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sindicato': {
      id: '/sindicato'
      path: '/sindicato'
      fullPath: '/sindicato'
      preLoaderRoute: typeof SindicatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/single': {
      id: '/single'
      path: '/single'
      fullPath: '/single'
      preLoaderRoute: typeof SingleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solitario': {
      id: '/solitario'
      path: '/solitario'
      fullPath: '/solitario'
      preLoaderRoute: typeof SolitarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torneo': {
      id: '/torneo'
      path: '/torneo'
      fullPath: '/torneo'
      preLoaderRoute: typeof TorneoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truco': {
      id: '/truco'
      path: '/truco'
      fullPath: '/truco'
      preLoaderRoute: typeof TrucoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  BagatelleRoute: BagatelleRoute,
  BlackjackRoute: BlackjackRoute,
  CamerinosRoute: CamerinosRoute,
  ChinchonRoute: ChinchonRoute,
  DadosRoute: DadosRoute,
  DiarioRoute: DiarioRoute,
  DificultadRoute: DificultadRoute,
  EncargosRoute: EncargosRoute,
  EscobaRoute: EscobaRoute,
  EstadisticasRoute: EstadisticasRoute,
  LogrosRoute: LogrosRoute,
  MahjongRoute: MahjongRoute,
  PokerRoute: PokerRoute,
  PrivacidadRoute: PrivacidadRoute,
  ProgresoRoute: ProgresoRoute,
  ReglasRoute: ReglasRoute,
  RuletaRoute: RuletaRoute,
  SindicatoRoute: SindicatoRoute,
  SingleRoute: SingleRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolitarioRoute: SolitarioRoute,
  TablesRoute: TablesRoute,
  TorneoRoute: TorneoRoute,
  TrucoRoute: TrucoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
